name: 'stable_diffusion_library_project'
description: 'WIP Stable Diffusion Is Library for generated text to Image'
version: '0.0.0'
repository: 'https://github.com/General-Developer/stable_diffusion_library'
homepage: 'https://www.youtube.com/@general_dev'
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
documentation: 'https://www.youtube.com/@general_dev'
funding:
  - 'https://github.com/sponsors/General-Developer'
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
  - 'https://github.com/sponsors/general-developer'
platforms:
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment:
  sdk: '>=3.7.0 <4.0.0'
dependencies:
  general_lib: '^0.0.66'
  packagex: '^0.0.85'
  path: '^1.9.0'
  yaml: '^3.1.3'
dev_dependencies:
  lints: '^5.0.0'
  test: 'any'
dependency_overrides:
  pointycastle: '3.8.0'
  mime: '^2.0.0'
project:
  type: 'library'
