name: 'stable_diffusion_app'
description: 'A new Flutter project.'
publish_to: 'none'
version: '1.0.0+1'
repository: 'https://github.com/General-Developer/whisper_library'
homepage: 'https://www.youtube.com/@general_dev'
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
documentation: 'https://www.youtube.com/@general_dev'
funding:
  - 'https://github.com/sponsors/General-Developer'
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
  - 'https://github.com/sponsors/general-developer'
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  flutter:
    sdk: 'flutter'
  cupertino_icons: '^1.0.8'
  general_lib: '^0.0.66'
  general_lib_flutter: '^0.0.41'
  packagex: '^0.0.85'
  simulate: '^0.0.52'
  general_framework: '^0.0.25'
  markdown_flutter: '^0.0.12'
  path: '^1.9.0'
  general_system_device: '^0.0.51'
  stable_diffusion_library: '^0.0.0'
  stable_diffusion_library_flutter: '^0.0.0'
  file_picker: '^8.3.5'
dev_dependencies:
  flutter_test:
    sdk: 'flutter'
  flutter_lints: '^5.0.0'
  msix: '^3.16.8'
flutter:
  uses-material-design: true
  
project:
  type: ''
dependency_overrides:
  pointycastle: '3.8.0'
  mime: '^2.0.0'
  stable_diffusion_library:
    path: '../../package/stable_diffusion_library'
  stable_diffusion_library_flutter:
    path: '../../package/stable_diffusion_library_flutter'
  archive:
    path: '/home/galaxeus/.pub-cache/hosted/pub.dev/archive-4.0.2'
  http:
    path: '/home/galaxeus/.pub-cache/hosted/pub.dev/http-1.2.2'
packagex:
  name: 'stable_diffusion_app'
  is_without_platform_name: true
  is_app_auto_clean_up_folder: true
  flutter_build_arguments: []
  dart_compile_exe_arguments: []
  uploads:
    - platform_type: 'github'
      github_username: 'archivon-apps-stores'
      github_tag: 'release'
      github_is_org: false
      github_repository_name: 'stable_diffusion_app'
    - platform_type: 'supabase'
      supabase_folder_name: 'release'
    - platform_type: 'telegram'
      telegram_chats:
        - chat_id: '@slebew'
          message_thread_id: ''
  packages:
    - dart_target: 'stable_diffusion_app'
      flutter_target: 'main'
      dart_name: 'stable_diffusion_app'
      flutter_name: 'stable_diffusion_app'
      output_name: 'stable-diffusion-app'
msix_config:
  display_name: 'stable_diffusion_app'
  install_certificate: false
