name: 'stable_diffusion_library_dart'
description: 'Stable Diffusion Is Library for generated Text To Image on Edge Device Without api key or internet quota'
version: '0.0.3'
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  stable_diffusion_library: '^0.0.3'
dev_dependencies:
  lints: '^5.0.0'
  test: 'any'
project:
  type: ''
dependency_overrides:
  pointycastle: '4.0.0'
  mime: '^2.0.0'
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
  - 'https://github.com/sponsors/general-developer'
homepage: 'https://www.youtube.com/@general_dev'
repository: 'https://github.com/General-Developer/stable_diffusion_library'
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
documentation: 'https://www.youtube.com/@general_dev'
platforms:
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
