name: 'stable_diffusion_library'
description: 'WIP Stable Diffusion Is Library for generated text to Image'
version: '0.0.0'
environment:
  sdk: '>=3.7.0 <4.0.0'
dependencies:
  general_lib: '^0.0.66'
  ffi: '^2.1.0'
  # crypto: '^3.0.3'
  path: '^1.9.0'
  # general_ml: '^0.0.2'
  ffi_universe: '^0.0.4'
dev_dependencies:
  lints: '^5.0.0'
  test: 'any'
  ffigen: '^15.0.0'
dependency_overrides:
  pointycastle: '3.8.0'
  mime: '^2.0.0'
flutter:
  uses-material-design: true
funding:
  - 'https://github.com/sponsors/azkadev'
  - 'https://github.com/sponsors/generalfoss'
  - 'https://github.com/sponsors/general-developer'
homepage: 'https://www.youtube.com/@general_dev'
repository: 'https://github.com/General-Developer/stable_diffusion_library'
issue_tracker: 'https://t.me/DEVELOPER_GLOBAL_PUBLIC'
documentation: 'https://www.youtube.com/@general_dev'
ffigen:
  name: 'StableDiffusionLibrarySharedBindingsByGeneralDeveloper'
  description: 'GeneralAiSpeechToTextLibraryWhisper Binding By General Corporation & Global Corporation & General Developer'
  output: 'lib/ffi/bindings.dart'
  headers:
    entry-points:
      - '../../native_lib/lib/stable_diffusion_library/include/stable_diffusion_library.h'
platforms:
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
project:
  type: ''
